### ISSUE TITLE
Update OpenMS Logos

### ISSUE THREAD

**Issue by jcharkow** [OpenMS/streamlit-template#169]
OpenMS recently got new logos. See https://github.com/OpenMS/images/blob/master/logos/FinalLogo_Nov2024_Versions-01.svg

Would be good if we could replace our existing logos (e.g. pyopenms logos below) with the general OpenMS logos.

![Image](https://github.com/user-attachments/assets/7b6c3664-121d-4d2d-80cd-f76ea5f3238f)

**Comment by Imama-Kainat** [comment]
Hi @jcharkow,  

I am also interested in working on this! I love the new OpenMS logo, and I was actually thinking that the current logo is not very visible in dark theme. Coincidentally, I came across this issue and would love to contribute.  

If @Srajald has not started yet, I’d be happy to take this on. Let me know how I can proceed. Thanks!

**Comment by jcharkow** [comment]
It seems that you both basically asked at the same time so I am happy if you decide amongst yourselves who wants to work on it. Currently, dark mode is not well supported (see https://github.com/OpenMS/streamlit-template/issues/168)

**Comment by achalbajpai** [comment]
@jcharkow 
I apologize for the inconvenience caused by this. I had begun updating this before the messages arrived as I was already working on dark theme model part, and I will definitely ensure that this doesn’t happen.

**Comment by achalbajpai** [comment]
Hello @t0mdavid-m and @jcharkow, this issue can be closed as - 

The necessary updates have been addressed in PR #170, and the changes are ready to be pushed.

**Comment by ketan1406** [comment]
Hi @jcharkow, the chages made from this issue were not able to accurately solve the issue as the changes donot reflect in the deployed streamlit website, st.image sometimes fails for SVG formats hence why the previous logos were in PNG format. 

Secondly, the blackFont image for the new logo tends to get absorbed into its background on switiching to dark mode, to tackle this I had made an earlier commit to [OpenMS/images](https://github.com/OpenMS/images/blob/master/logos/OpenMS_transparent_whiteFont_blackOutline.svg), this includes the new logo with a blackOutline, this image works for both dark and light mode. This is also works for favicons and other places where we cannot control the theme.

Thirdly the ico file for the windows exec build is still old, I tested the build with the new logo `openms.ico`, you can check the solution [here](https://github.com/ketan1406/streamlit-template/tree/dev)

![Image](https://github.com/user-attachments/assets/0bf53152-58a5-46e6-b52e-4e7ec9b7a53a)
![Image](https://github.com/user-attachments/assets/dcb8871d-57ec-4e11-bc27-d40f7dbf01f8)

![Image](https://github.com/user-attachments/assets/f634518a-06f6-495f-8ae0-bcf9bea5ff30)

This is the windows installation after adding the new ico file:
 
![Image](https://github.com/user-attachments/assets/39ab9c1d-92ae-4136-9061-df68eec31065)


If you want I can raise a PR solving this issue, as I have already solved this issue.

**Comment by jcharkow** [comment]
Thank you for examining this.  Yes feel free to raise a PR and I will review it.

**Comment by t0mdavid-m** [comment]
Note that the website needs to be updated manually and I have not done that yet. Do the issues persist if you run this locally?

**Comment by ketan1406** [comment]
@t0mdavid-m , the issue does not persist when ran locally, but when deployed from what I came across on the internet st.image has some issues with the [SVG format](https://github.com/streamlit/streamlit/issues/9098), you can also check out this [link](https://github.com/streamlit/streamlit/issues/3882)  , maybe its the manual changes due to which the changes haven't yet reflected but the old logo was in PNG format so I believe it should not be a problem if we add a PNG for the new logo. 

- Additionally as shown below the current logo disappears in a dark theme, I had encountered this problem in other OpenMS repos, due to which I made the blackOutline SVG in the OpenMS/images repo

![Image](https://github.com/user-attachments/assets/11ed3e61-3bc8-4648-8000-677d0eb58e18)

- This is what my solution looks like 

![Image](https://github.com/user-attachments/assets/07b94a55-ca42-4563-aa14-829511692bcc)

If you say I can leave these changes as they are and only raise a PR for the windows exec ICO file

**Comment by achalbajpai** [comment]
> [@t0mdavid-m](https://github.com/t0mdavid-m) , the issue does not persist when ran locally, but when deployed from what I came across on the internet st.image has some issues with the [SVG format](https://github.com/streamlit/streamlit/issues/9098), you can also check out this [link](https://github.com/streamlit/streamlit/issues/3882) , maybe its the manual changes due to which the changes haven't yet reflected but the old logo was in PNG format so I believe it should not be a problem if we add a PNG for the new logo.
> 
> * Additionally as shown below the current logo disappears in a dark theme, I had encountered this problem in other OpenMS repos, due to which I made the blackOutline SVG in the OpenMS/images repo
> 
> ![Image](https://github.com/user-attachments/assets/11ed3e61-3bc8-4648-8000-677d0eb58e18)
> 
> * This is what my solution looks like
> 
> ![Image](https://github.com/user-attachments/assets/07b94a55-ca42-4563-aa14-829511692bcc)
> 
> If you say I can leave these changes as they are and only raise a PR for the windows exec ICO file


Hi , 

I took a deeper dive into this and found out this = 

We're using the SVG logo in three places—once with `st.logo()` second with `st.set_page_config()`. I don't feel there will be an issue regarding both of them - as there has been nothing reported ( as checked for now ) 

Now coming to the third place in the `quickstart.py` where we use `st.image()`
This issue has been raised a quite number of times in the past years as you mentioned and there have been solutions that helps you deploy with no issues. 

https://docs.streamlit.io/develop/api-reference/media/st.image

The version we're using (1.38.0) has some improved SVG support compared to earlier versions, the original issues were reported in earlier versions like 1.36.0, particularly around width settings.


That said, if we do run into deployment issues, we have some easy workarounds—switching to a PNG (like you suggested) or the best way would be using img tag as suggested in https://github.com/streamlit/streamlit/pull/7183 , if we are looking for a full out solution here.

Some prs that solves the issue related to svg in st.image() -
https://github.com/streamlit/streamlit/pull/7183




Since everything works smoothly in our local setup, we can stick with SVG . If we hit any tend to hit any rendering issues after deployment, we can explore other options then as the issue exists with some .

**Comment by ketan1406** [comment]
Hi @achalbajpai, sure, we can stick with SVG file format.  I will still raise a PR with the whiteFont-blackOutline SVGs since the blackFont tends to cause visibility issues in darker themes and streamlit won't let us dynamically change logos/images on theme change.
